CREATE OR REPLACE DATABASE RESTAURANT_DB;

USE DATABASE RESTAURANT_DB;

CREATE OR REPLACE SCHEMA BRONZE;

CREATE OR REPLACE SCHEMA SILVER;

CREATE OR REPLACE SCHEMA GOLD;


SHOW SCHEMAS;

-----------------------------------------------------
USE SCHEMA BRONZE;
CREATE OR REPLACE STAGE RESTAURANT_STAGE;
SHOW STAGES;

list @restaurant_db.bronze.restaurant_stage;
---------------------------------------------------------
-- create the bronze tables
CREATE OR REPLACE TABLE BRONZE_CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    LOYALTY_TIER VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    UPDATED_AT TIMESTAMP
);
DESC TABLE BRONZE_CUSTOMERS;


--loading data
USE DATABASE RESTAURANT_DB;
USE SCHEMA BRONZE;

COPY INTO BRONZE_CUSTOMERS
FROM @RESTAURANT_STAGE/restaurant_customers_expanded.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);
SELECT COUNT(*) 
FROM BRONZE_CUSTOMERS;

--bronze_orders tables

CREATE OR REPLACE TABLE BRONZE_ORDERS (
    ORDER_ID VARCHAR,
    ORDER_LINE_ID VARCHAR,
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR,
    MENU_ITEM_ID VARCHAR,
    RESTAURANT_ID VARCHAR,
    ORDER_CHANNEL VARCHAR,
    QTY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT_PCT NUMBER(5,2),
    PAYMENT_TYPE VARCHAR,
    ORDER_STATUS VARCHAR
);

DESC TABLE BRONZE_ORDERS;

USE DATABASE RESTAURANT_DB;
USE SCHEMA BRONZE;

COPY INTO BRONZE_ORDERS
FROM @RESTAURANT_STAGE/restaurant_orders_expanded.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);
SELECT COUNT(*)
FROM BRONZE_ORDERS;
SELECT *
FROM BRONZE_ORDERS
LIMIT 10;



CREATE OR REPLACE TABLE BRONZE_MENU_ITEMS (
    MENU_ITEM_ID VARCHAR,
    ITEM_NAME VARCHAR,
    ITEM_TYPE VARCHAR,
    CUISINE VARCHAR,
    DIET_TYPE VARCHAR,
    LIST_PRICE NUMBER(10,2),
    STATUS VARCHAR,
    UPDATED_AT TIMESTAMP
);

DESC TABLE BRONZE_MENU_ITEMS;


COPY INTO BRONZE_MENU_ITEMS
FROM @RESTAURANT_STAGE/menu_items_expanded.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);

SELECT COUNT(*)
FROM BRONZE_MENU_ITEMS;

SELECT *
FROM BRONZE_MENU_ITEMS
LIMIT 10;

CREATE OR REPLACE TABLE BRONZE_LOCATIONS (
    RESTAURANT_ID VARCHAR,
    RESTAURANT_NAME VARCHAR,
    REGION VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    OPEN_DATE DATE,
    SERVICE_MODES VARCHAR,
    STATUS VARCHAR
);

COPY INTO BRONZE_LOCATIONS
FROM @RESTAURANT_STAGE/restaurant_locations_expanded.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);

SELECT COUNT(*) FROM BRONZE_LOCATIONS;

SELECT *
FROM BRONZE_LOCATIONS
LIMIT 10;

drop table bronze_delivery;
CREATE OR REPLACE TABLE BRONZE_DELIVERY (
    ORDER_ID VARCHAR,
    DELIVERY_PARTNER VARCHAR,
    DISTANCE_KM NUMBER(10,2),
    PREP_TIME_MIN NUMBER,
    DELIVERY_TIME_MIN NUMBER,
    DELIVERY_STATUS VARCHAR
);



COPY INTO BRONZE_DELIVERY
FROM @RESTAURANT_STAGE/restaurant_delivery.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);
SELECT COUNT(*)
FROM BRONZE_DELIVERY;

SELECT *
FROM BRONZE_DELIVERY
LIMIT 10;


CREATE OR REPLACE TABLE BRONZE_REVIEWS (
    REVIEW_ID VARCHAR,
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    RESTAURANT_ID VARCHAR,
    RATING NUMBER,
    REVIEW_CATEGORY VARCHAR,
    REVIEW_DATE DATE
);

COPY INTO BRONZE_REVIEWS
FROM @RESTAURANT_STAGE/restaurant_reviews.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);


CREATE OR REPLACE TABLE BRONZE_MASTER_ANALYTICS (
    ORDER_ID VARCHAR,
    ORDER_LINE_ID NUMBER,
    ORDER_DATE DATE,
    CUSTOMER_ID VARCHAR,
    MENU_ITEM_ID VARCHAR,
    RESTAURANT_ID VARCHAR,
    ORDER_CHANNEL VARCHAR,
    QTY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT_PCT NUMBER(5,2),
    PAYMENT_TYPE VARCHAR,
    ORDER_STATUS VARCHAR,

    MENU_MENU_ITEM_ID VARCHAR,
    MENU_ITEM_NAME VARCHAR,
    MENU_ITEM_TYPE VARCHAR,
    MENU_CUISINE VARCHAR,
    MENU_DIET_TYPE VARCHAR,
    MENU_LIST_PRICE NUMBER(10,2),
    MENU_STATUS VARCHAR,
    MENU_UPDATED_AT TIMESTAMP,

    REST_RESTAURANT_ID VARCHAR,
    REST_RESTAURANT_NAME VARCHAR,
    REST_REGION VARCHAR,
    REST_CITY VARCHAR,
    REST_STATE VARCHAR,
    REST_COUNTRY VARCHAR,
    REST_OPEN_DATE DATE,
    REST_SERVICE_MODES VARCHAR,
    REST_STATUS VARCHAR,

    CUST_CUSTOMER_ID VARCHAR,
    CUST_FIRST_NAME VARCHAR,
    CUST_LAST_NAME VARCHAR,
    CUST_EMAIL VARCHAR,
    CUST_PHONE VARCHAR,
    CUST_LOYALTY_TIER VARCHAR,
    CUST_CITY VARCHAR,
    CUST_STATE VARCHAR,
    CUST_COUNTRY VARCHAR,
    CUST_UPDATED_AT TIMESTAMP,

    CUSTOMER_RATING NUMBER(3,1),
    REVIEW_COUNT NUMBER,

    DELIVERY_PARTNER VARCHAR,
    DISTANCE_KM NUMBER(10,2),
    PREP_TIME_MIN NUMBER,
    DELIVERY_TIME_MIN NUMBER,
    DELIVERY_STATUS VARCHAR,

    GROSS_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    NET_AMOUNT NUMBER(10,2)
);

COPY INTO BRONZE_MASTER_ANALYTICS
FROM @RESTAURANT_STAGE/restaurant_master_analytics.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
);


---------------------------------------
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    CREATED
FROM RESTAURANT_DB.INFORMATION_SCHEMA.TABLES
WHERE UPPER(TABLE_NAME) = 'STG_CUSTOMERS'
ORDER BY CREATED DESC;

SHOW TABLES IN SCHEMA RESTAURANT_DB.SILVER;

SELECT *
FROM RESTAURANT_DB.SILVER.STG_CUSTOMERS
LIMIT 10;



SHOW TABLES IN SCHEMA RESTAURANT_DB.SILVER;
SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;
select * from silver_delivery;
select * from silver_customers;
select * from silver_menu_items;
select * from silver_locations;
select * from silver_orders;
select * from silver_reviews;
select * from dim_customer;
select * from dim_date;
select * from dim_menu_item;
select * from dim_restaurant;
select * from fact_orders;
drop table fact_orders;

SELECT *
FROM RESTAURANT_DB.GOLD.FACT_ORDERS
LIMIT 10;



SELECT *
FROM RESTAURANT_DB.GOLD.FACT_ORDERS
LIMIT 10;



SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(ORDER_ID IS NULL) AS NULL_ORDER_ID,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(MENU_ITEM_ID IS NULL) AS NULL_MENU_ITEM_ID,
    COUNT_IF(RESTAURANT_ID IS NULL) AS NULL_RESTAURANT_ID,
    COUNT_IF(NET_AMOUNT IS NULL) AS NULL_NET_AMOUNT,
    COUNT_IF(DELIVERY_PARTNER IS NULL) AS NULL_DELIVERY,
    COUNT_IF(RATING IS NULL) AS NULL_RATING
FROM RESTAURANT_DB.GOLD.FACT_ORDERS;




SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RESTAURANT_DB.GOLD.DIM_CUSTOMER

UNION ALL

SELECT 'DIM_MENU_ITEM', COUNT(*)
FROM RESTAURANT_DB.GOLD.DIM_MENU_ITEM

UNION ALL

SELECT 'DIM_RESTAURANT', COUNT(*)
FROM RESTAURANT_DB.GOLD.DIM_RESTAURANT

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM RESTAURANT_DB.GOLD.DIM_DATE

UNION ALL

SELECT 'FACT_ORDERS', COUNT(*)
FROM RESTAURANT_DB.GOLD.FACT_ORDERS;





SELECT
    COUNT(*) AS TOTAL_FACT_ROWS,
    COUNT_IF(c.CUSTOMER_ID IS NULL) AS INVALID_CUSTOMERS,
    COUNT_IF(m.MENU_ITEM_ID IS NULL) AS INVALID_MENU_ITEMS,
    COUNT_IF(r.RESTAURANT_ID IS NULL) AS INVALID_RESTAURANTS,
    COUNT_IF(d.DATE IS NULL) AS INVALID_DATES
FROM RESTAURANT_DB.GOLD.FACT_ORDERS f
LEFT JOIN RESTAURANT_DB.GOLD.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN RESTAURANT_DB.GOLD.DIM_MENU_ITEM m
    ON f.MENU_ITEM_ID = m.MENU_ITEM_ID
LEFT JOIN RESTAURANT_DB.GOLD.DIM_RESTAURANT r
    ON f.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN RESTAURANT_DB.GOLD.DIM_DATE d
    ON f.ORDER_DATE = d.DATE;


SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;
select * from customer_snapshot;


SELECT
    CUSTOMER_ID,
    LOYALTY_TIER,
    DBT_VALID_FROM,
    DBT_VALID_TO
FROM RESTAURANT_DB.GOLD.CUSTOMER_SNAPSHOT
LIMIT 10;




SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(DBT_VALID_TO IS NULL) AS CURRENT_RECORDS,
    COUNT_IF(DBT_VALID_TO IS NOT NULL) AS HISTORICAL_RECORDS
FROM RESTAURANT_DB.GOLD.CUSTOMER_SNAPSHOT;

SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;
select * from menu_item_snapshot;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(DBT_VALID_TO IS NULL) AS CURRENT_RECORDS,
    COUNT_IF(DBT_VALID_TO IS NOT NULL) AS HISTORICAL_RECORDS
FROM RESTAURANT_DB.GOLD.MENU_ITEM_SNAPSHOT;




SHOW VIEWS IN SCHEMA RESTAURANT_DB.GOLD;
SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;




SELECT
    SUM(NET_AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QTY) AS TOTAL_ITEMS_SOLD,
    ROUND(
        SUM(NET_AMOUNT) / COUNT(DISTINCT ORDER_ID),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM RESTAURANT_DB.GOLD.FACT_ORDERS;



SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_DATE
ORDER BY ORDER_DATE
LIMIT 10;


SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_RESTAURANT
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;




SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_MENU_ITEM
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;




SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_CUISINE
ORDER BY TOTAL_REVENUE DESC;



SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_CHANNEL
ORDER BY TOTAL_REVENUE DESC;



SELECT *
FROM RESTAURANT_DB.GOLD.REVENUE_BY_LOYALTY_TIER
ORDER BY TOTAL_REVENUE DESC;



SELECT *
FROM RESTAURANT_DB.GOLD.DELIVERY_PERFORMANCE
ORDER BY AVG_TOTAL_DELIVERY_TIME_MIN;



SELECT *
FROM RESTAURANT_DB.GOLD.CUSTOMER_REVIEW_ANALYSIS
ORDER BY AVG_RATING DESC;



SELECT *
FROM RESTAURANT_DB.GOLD.ORDER_STATUS_ANALYSIS
ORDER BY TOTAL_ORDERS DESC;


SELECT *
FROM RESTAURANT_DB.GOLD.KPI_SUMMARY;


SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;
SHOW VIEWS IN SCHEMA RESTAURANT_DB.GOLD;


SELECT
    ROUND(AVG(NULLIF(RATING, 0)), 2) AS CORRECT_AVG_RATING
FROM RESTAURANT_DB.GOLD.FACT_ORDERS;

SELECT
    TOTAL_ORDERS,
    TOTAL_ITEMS_SOLD,
    TOTAL_REVENUE,
    AVERAGE_ORDER_VALUE,
    AVERAGE_RATING
FROM RESTAURANT_DB.GOLD.KPI_SUMMARY;


show warehouses;


USE DATABASE RESTAURANT_DB;
USE WAREHOUSE MY_WAREHOUSE;

CREATE OR REPLACE STORAGE INTEGRATION RESTAURANT_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN_HIDDEN>'
  STORAGE_ALLOWED_LOCATIONS = (
      's3://restaurant-analytics-data-vikas/raw/'
  );
  DESC INTEGRATION RESTAURANT_S3_INTEGRATION;



  CREATE OR REPLACE STORAGE INTEGRATION RESTAURANT_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<AWS_ROLE_ARN_HIDDEN>'
  STORAGE_ALLOWED_LOCATIONS = (
      's3://restaurant-analytics-data-vikas/raw/'
  );
  DESC INTEGRATION RESTAURANT_S3_INTEGRATION;


  CREATE OR REPLACE STAGE RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE
  URL = 's3://restaurant-analytics-data-vikas/raw/'
  STORAGE_INTEGRATION = RESTAURANT_S3_INTEGRATION
  FILE_FORMAT = (
      TYPE = CSV
      SKIP_HEADER = 1
      FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  );
  LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;



SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
    'RESTAURANT_S3_INTEGRATION',
    's3://restaurant-analytics-data-vikas/raw/',
    'restaurant_orders_expanded.csv',
    'read'
);



DESC INTEGRATION RESTAURANT_S3_INTEGRATION;


SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
    'RESTAURANT_S3_INTEGRATION',
    's3://restaurant-analytics-data-vikas/raw/',
    'restaurant_orders_expanded.csv',
    'list'
);

DESC INTEGRATION RESTAURANT_S3_INTEGRATION;
DESC INTEGRATION RESTAURANT_S3_INTEGRATION;
SELECT CURRENT_REGION();



LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;
LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;



ALTER STORAGE INTEGRATION RESTAURANT_S3_INTEGRATION
SET STORAGE_AWS_ROLE_ARN =
'<AWS_ROLE_ARN_HIDDEN>';

ALTER STORAGE INTEGRATION RESTAURANT_S3_INTEGRATION
SET STORAGE_AWS_ROLE_ARN =
'<AWS_ROLE_ARN_HIDDEN>';
LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;


LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;

ALTER STORAGE INTEGRATION RESTAURANT_S3_INTEGRATION
SET STORAGE_AWS_EXTERNAL_ID = '<AWS_EXTERNAL_ID_HIDDEN>';



DESC INTEGRATION RESTAURANT_S3_INTEGRATION;
LIST @RESTAURANT_DB.BRONZE.RESTAURANT_S3_STAGE;
DESC INTEGRATION RESTAURANT_S3_INTEGRATION;





CREATE OR REPLACE STAGE RESTAURANT_S3_STAGE1
URL = 's3://restaurant-analytics-data-vikas/raw/'
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_KEY_ID_HIDDEN>'
    AWS_SECRET_KEY = '<AWS_SECRET_KEY_HIDDEN>')
      FILE_FORMAT = (
      TYPE = CSV
      SKIP_HEADER = 1
      FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  );
  LIST @RESTAURANT_S3_STAGE1;


  ------------------------------------------------------
  LIST @RESTAURANT_S3_STAGE1;
  DESC TABLE RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS;
SELECT
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
FROM @RESTAURANT_S3_STAGE1
(
    PATTERN => '.*restaurant_customers.*\.csv'
)
LIMIT 5;
----------snow pipes----------------------

CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_customers.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS
REFRESH;


SELECT COUNT(*) AS CUSTOMER_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS;


SELECT *
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS
LIMIT 5;





  CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_ORDERS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_ORDERS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_orders.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_ORDERS
REFRESH;
SELECT COUNT(*) AS ORDER_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_ORDERS;


CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_menu.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
SELECT COUNT(*) AS MENU_ITEM_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS
REFRESH;

CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_LOCATIONS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_LOCATIONS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_locations.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_LOCATIONS
REFRESH;

CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_DELIVERY
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_DELIVERY
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_delivery.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_DELIVERY
REFRESH;
CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_REVIEWS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_REVIEWS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_reviews.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_REVIEWS
REFRESH;

DESC TABLE RESTAURANT_DB.BRONZE.BRONZE_MASTER_ANALYTICS;
CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_MASTER_ANALYTICS
AUTO_INGEST = FALSE
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_MASTER_ANALYTICS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_master_analytics.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
ALTER PIPE RESTAURANT_DB.BRONZE.PIPE_MASTER_ANALYTICS
REFRESH;
SELECT COUNT(*) AS MASTER_ANALYTICS_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_MASTER_ANALYTICS;



SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS

UNION ALL

SELECT 'ORDERS', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_ORDERS

UNION ALL

SELECT 'MENU_ITEMS', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS

UNION ALL

SELECT 'LOCATIONS', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_LOCATIONS

UNION ALL

SELECT 'DELIVERY', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_DELIVERY

UNION ALL

SELECT 'REVIEWS', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_REVIEWS

UNION ALL

SELECT 'MASTER_ANALYTICS', COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_MASTER_ANALYTICS;



SHOW TABLES IN SCHEMA RESTAURANT_DB.SILVER;
SHOW TABLES IN SCHEMA RESTAURANT_DB.GOLD;



SHOW PIPES IN SCHEMA RESTAURANT_DB.BRONZE;

DESC PIPE RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS;

SHOW NOTIFICATION INTEGRATIONS;



CREATE NOTIFICATION INTEGRATION RESTAURANT_S3_NOTIFICATION
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AWS_SNS
  DIRECTION = INBOUND
  AWS_SNS_TOPIC_ARN = 'YOUR_SNS_TOPIC_ARN';


  SELECT SYSTEM$GET_AWS_SNS_IAM_POLICY(
    '<AWS_SNS_TOPIC_ARN_HIDDEN>'
);
CREATE OR REPLACE PIPE PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO BRONZE_CUSTOMERS
FROM @RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_customers.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);






CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_customers.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


SHOW PIPES LIKE 'PIPE_CUSTOMERS'
IN SCHEMA RESTAURANT_DB.BRONZE;



SHOW PIPES LIKE 'PIPE_CUSTOMERS'
IN SCHEMA RESTAURANT_DB.BRONZE;

SHOW PIPES LIKE 'PIPE_CUSTOMERS'
IN SCHEMA RESTAURANT_DB.BRONZE;


SELECT SYSTEM$PIPE_STATUS(
    'RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS'
);


SELECT SYSTEM$PIPE_STATUS(
    'RESTAURANT_DB.BRONZE.PIPE_CUSTOMERS'
);

SELECT COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS;


CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_ORDERS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_ORDERS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_orders.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_menu.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_LOCATIONS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_LOCATIONS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_locations.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_DELIVERY
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_DELIVERY
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_delivery.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);
CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_REVIEWS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_REVIEWS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*restaurant_reviews.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


SELECT
    PIPE_NAME,
    IS_AUTOINGEST_ENABLED,
    NOTIFICATION_CHANNEL_NAME
FROM RESTAURANT_DB.INFORMATION_SCHEMA.PIPES
WHERE PIPE_SCHEMA = 'BRONZE'
  AND PIPE_NAME IN (
      'PIPE_CUSTOMERS',
      'PIPE_ORDERS',
      'PIPE_MENU_ITEMS',
      'PIPE_LOCATIONS',
      'PIPE_DELIVERY',
      'PIPE_REVIEWS'
  )
ORDER BY PIPE_NAME;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ORDER_ID) AS UNIQUE_ORDERS,
    COUNT_IF(ORDER_ID IS NULL) AS NULL_ORDER_IDS,
    COUNT_IF(ORDER_DATE IS NULL) AS NULL_ORDER_DATES
FROM RESTAURANT_DB.BRONZE.BRONZE_ORDERS;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_IDS,
    COUNT_IF(EMAIL IS NULL) AS NULL_EMAILS
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT REVIEW_ID) AS UNIQUE_REVIEWS,
    COUNT_IF(REVIEW_ID IS NULL) AS NULL_REVIEW_IDS,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_IDS,
    COUNT_IF(RATING IS NULL) AS NULL_RATINGS
FROM RESTAURANT_DB.BRONZE.BRONZE_REVIEWS;
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT MENU_ITEM_ID) AS UNIQUE_MENU_ITEMS,
    COUNT_IF(MENU_ITEM_ID IS NULL) AS NULL_MENU_ITEM_IDS,
    COUNT_IF(ITEM_NAME IS NULL) AS NULL_ITEM_NAMES,
    COUNT_IF(LIST_PRICE IS NULL) AS NULL_LIST_PRICES
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;


DESC TABLE RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;



SELECT COUNT(*)
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;

SELECT SYSTEM$PIPE_STATUS(
    'RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS'
);
CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*menu_items.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


SELECT COUNT(*) AS MENU_ITEM_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;

LIST @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1;

CREATE OR REPLACE PIPE RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = '<AWS_SNS_TOPIC_ARN_HIDDEN>'
AS
COPY INTO RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS
FROM @RESTAURANT_DB.PUBLIC.RESTAURANT_S3_STAGE1
PATTERN = '.*menu_items.*\.csv'
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


SELECT SYSTEM$PIPE_STATUS(
    'RESTAURANT_DB.BRONZE.PIPE_MENU_ITEMS'
);

SELECT COUNT(*) AS MENU_ITEM_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_MENU_ITEMS;


SELECT COUNT(*) AS TOTAL_CUSTOMER_RECORDS
FROM RESTAURANT_DB.BRONZE.BRONZE_CUSTOMERS;

select * from bronze_customers;

SELECT SYSTEM$PIPE_STATUS(
    'RESTAURANT_DB.BRONZE.PIPE_REVIEWS'
);
SELECT COUNT(*) AS REVIEW_COUNT
FROM RESTAURANT_DB.BRONZE.BRONZE_REVIEWS;


SELECT *
FROM RESTAURANT_DB.GOLD.CUSTOMER_REVIEW_ANALYSIS
ORDER BY 1;